window.MOVIE_TABLE = [
  { id: 1, title: 'The Exorcist', titleRu: 'Изгоняющий дьявола', year: 1973, duration: 122, genre: 'supernatural', genreLabelEn: 'Supernatural', genreLabelRu: 'Мистика', countryEn: 'USA', countryRu: 'США', rating: 8.1, poster: 'images/exorcist.jpg', backdrop: 'images/exorcist.jpg', pageTextEn: 'A possession story that begins with doubt and ritual and slowly turns one family home into the center of a private apocalypse.', pageTextRu: 'История одержимости, которая начинается с сомнений и ритуала, а затем превращает семейный дом в центр личного апокалипсиса.', cardTextEn: 'Classic possession horror with a severe tone, careful pacing and a final image that still feels unsettling.', cardTextRu: 'Классический хоррор об одержимости с жёстким тоном, выверенным темпом и сильным финальным образом.', moodsEn: ['ritual', 'classic', 'possession'], moodsRu: ['ритуал', 'классика', 'одержимость'] },
  { id: 2, title: 'The Shining', titleRu: 'Сияние', year: 1980, duration: 146, genre: 'psychological', genreLabelEn: 'Psychological', genreLabelRu: 'Психологический', countryEn: 'UK / USA', countryRu: 'Великобритания / США', rating: 8.4, poster: 'images/shining.jpg', backdrop: 'images/shining.jpg', pageTextEn: 'A family isolated in a mountain hotel loses its balance as the building itself begins to shape memory, anger and fear.', pageTextRu: 'Семья, запертая в горном отеле, постепенно теряет равновесие, пока само пространство не начинает управлять памятью, злостью и страхом.', cardTextEn: 'Cold and precise horror about isolation, repetition and a place that never feels empty.', cardTextRu: 'Холодный и точный фильм об изоляции, повторении и пространстве, которое никогда не кажется пустым.', moodsEn: ['isolation', 'classic', 'winter'], moodsRu: ['изоляция', 'классика', 'зима'] },
  { id: 3, title: 'Suspiria', titleRu: 'Суспирия', year: 2018, duration: 152, genre: 'supernatural', genreLabelEn: 'Supernatural', genreLabelRu: 'Мистика', countryEn: 'Italy / USA', countryRu: 'Италия / США', rating: 6.7, poster: 'images/suspiria.jpg', backdrop: 'images/suspiria.jpg', pageTextEn: 'A dance academy hides a rigid ritual order where discipline, beauty and violence are inseparable.', pageTextRu: 'Танцевальная академия скрывает ритуальный порядок, в котором дисциплина, красота и насилие существуют вместе.', cardTextEn: 'Occult horror with strong visual rhythm, ritual energy and an oppressive mood.', cardTextRu: 'Оккультный хоррор с сильным визуальным ритмом, ритуальной энергией и гнетущим настроением.', moodsEn: ['ritual', 'dance', 'art-house'], moodsRu: ['ритуал', 'танец', 'артхаус'] },
  { id: 4, title: 'Hereditary', titleRu: 'Реинкарнация', year: 2018, duration: 127, genre: 'psychological', genreLabelEn: 'Psychological', genreLabelRu: 'Психологический', countryEn: 'USA', countryRu: 'США', rating: 7.3, poster: 'images/hereditary.jpg', backdrop: 'images/hereditary.jpg', pageTextEn: 'Family grief opens the way to a larger design in which every new detail feels planned long before the first tragedy.', pageTextRu: 'Семейное горе открывает путь большому замыслу, где каждая новая деталь словно была подготовлена задолго до первой трагедии.', cardTextEn: 'A family horror built on grief, unease and a slow crushing escalation.', cardTextRu: 'Семейный хоррор, построенный на горе, тревоге и медленном, давящем нарастании.', moodsEn: ['family', 'grief', 'ritual'], moodsRu: ['семья', 'горе', 'ритуал'] },
  { id: 5, title: 'Saw', titleRu: 'Пила', year: 2004, duration: 103, genre: 'thriller', genreLabelEn: 'Thriller', genreLabelRu: 'Триллер', countryEn: 'USA', countryRu: 'США', rating: 7.6, poster: 'images/saw.jpg', backdrop: 'images/saw.jpg', pageTextEn: 'A trap-driven thriller where fear grows from forced choices, time pressure and the feeling that someone has already written the rules.', pageTextRu: 'Триллер-ловушка, где страх рождается из вынужденного выбора, давления времени и ощущения, что правила уже кем-то написаны.', cardTextEn: 'A tense locked-room thriller focused on moral pressure, time and survival.', cardTextRu: 'Напряжённый триллер в замкнутом пространстве о моральном давлении, времени и выживании.', moodsEn: ['trap', 'pressure', 'crime'], moodsRu: ['ловушка', 'давление', 'преступление'] },
  { id: 6, title: 'The Omen', titleRu: 'Омен', year: 1976, duration: 111, genre: 'supernatural', genreLabelEn: 'Supernatural', genreLabelRu: 'Мистика', countryEn: 'UK / USA', countryRu: 'Великобритания / США', rating: 7.5, poster: 'images/omen.jpg', backdrop: 'images/omen.jpg', pageTextEn: 'A polished occult story where prophecy, status and parental fear collide with a quiet but relentless force.', pageTextRu: 'Выверенная оккультная история, где пророчество, статус и родительский страх сталкиваются с тихой, но неумолимой силой.', cardTextEn: 'Religious dread, formal atmosphere and one of the most recognizable occult thrillers.', cardTextRu: 'Религиозная тревога, строгая атмосфера и один из самых узнаваемых оккультных триллеров.', moodsEn: ['prophecy', 'classic', 'church'], moodsRu: ['пророчество', 'классика', 'церковь'] },
  { id: 7, title: 'Midsommar', titleRu: 'Солнцестояние', year: 2019, duration: 148, genre: 'supernatural', genreLabelEn: 'Supernatural', genreLabelRu: 'Мистика', countryEn: 'USA / Sweden', countryRu: 'США / Швеция', rating: 7.4, poster: 'images/midsommar.jpg', backdrop: 'images/midsommar.jpg', pageTextEn: 'A summer trip turns into a staged communal ritual where daylight makes everything even less safe.', pageTextRu: 'Летняя поездка превращается в тщательно поставленный коллективный ритуал, где яркий дневной свет делает происходящее ещё страшнее.', cardTextEn: 'Folk horror where beauty, order and violence stay visible at the same time.', cardTextRu: 'Фолк-хоррор, в котором красота, порядок и насилие существуют одновременно и открыто.', moodsEn: ['summer', 'ritual', 'folk'], moodsRu: ['лето', 'ритуал', 'фолк'] },
  { id: 8, title: 'The Babadook', titleRu: 'Бабадук', year: 2014, duration: 94, genre: 'psychological', genreLabelEn: 'Psychological', genreLabelRu: 'Психологический', countryEn: 'Australia', countryRu: 'Австралия', rating: 6.8, poster: 'images/babadook.jpg', backdrop: 'images/babadook.jpg', pageTextEn: 'A strange children’s book becomes the trigger for fear that settles inside a house and starts feeding on grief.', pageTextRu: 'Странная детская книга становится спусковым крючком для страха, который поселяется в доме и питается горем.', cardTextEn: 'Compact domestic horror with a memorable central image and steady psychological pressure.', cardTextRu: 'Компактный домашний хоррор с сильным центральным образом и устойчивым психологическим давлением.', moodsEn: ['home', 'grief', 'shadow'], moodsRu: ['дом', 'горе', 'тень'] },
  { id: 9, title: 'The Conjuring', titleRu: 'Заклятие', year: 2013, duration: 112, genre: 'supernatural', genreLabelEn: 'Supernatural', genreLabelRu: 'Мистика', countryEn: 'USA', countryRu: 'США', rating: 7.5, poster: 'images/conjuring.jpg', backdrop: 'images/conjuring.jpg', pageTextEn: 'A haunted-house case begins like field work and then breaks into full supernatural panic.', pageTextRu: 'История о проклятом доме начинается почти как полевое расследование, а затем превращается в открытую сверхъестественную панику.', cardTextEn: 'A polished haunted-house film with measured buildup and a confident payoff.', cardTextRu: 'Выверенный фильм о проклятом доме с аккуратным наращиванием напряжения и сильной развязкой.', moodsEn: ['haunted-house', 'case', 'family'], moodsRu: ['дом', 'дело', 'семья'] },
  { id: 10, title: '1408', titleRu: '1408', year: 2007, duration: 104, genre: 'thriller', genreLabelEn: 'Thriller', genreLabelRu: 'Триллер', countryEn: 'USA', countryRu: 'США', rating: 6.8, poster: 'images/1408.jpg', backdrop: 'images/1408.jpg', pageTextEn: 'A skeptical writer checks into a notorious hotel room and finds a closed system built from memory, mockery and repetition.', pageTextRu: 'Скептически настроенный писатель заселяется в печально известный гостиничный номер и попадает в замкнутую систему памяти, издёвки и повторения.', cardTextEn: 'Hotel-room paranoia with a direct premise and a strong psychological hook.', cardTextRu: 'Параноидальный триллер о гостиничном номере с ясной идеей и сильной психологической основой.', moodsEn: ['hotel', 'room', 'loop'], moodsRu: ['отель', 'номер', 'петля'] },
  { id: 11, title: 'Shutter Island', titleRu: 'Остров проклятых', year: 2010, duration: 138, genre: 'thriller', genreLabelEn: 'Thriller', genreLabelRu: 'Триллер', countryEn: 'USA', countryRu: 'США', rating: 8.2, poster: 'images/shutter-island.jpg', backdrop: 'images/shutter-island.jpg', pageTextEn: 'An investigation on an isolated island turns into a personal collapse where setting and state of mind move together.', pageTextRu: 'Расследование на изолированном острове превращается в личную катастрофу, где пространство и состояние сознания движутся вместе.', cardTextEn: 'A stormy thriller driven by confinement, suspicion and unstable memory.', cardTextRu: 'Мрачный триллер, построенный на изоляции, подозрении и нестабильной памяти.', moodsEn: ['storm', 'clinic', 'mystery'], moodsRu: ['шторм', 'клиника', 'тайна'] }
];

window.COLLECTION_TABLE = [
  { id: 'c1', titleEn: 'Ritual and belief', titleRu: 'Ритуал и вера', textEn: 'Films where religion, ceremony or inherited rules shape the threat long before the final scene.', textRu: 'Фильмы, где религия, ритуал или унаследованные правила задают угрозу задолго до финала.', items: [1, 3, 6, 7] },
  { id: 'c2', titleEn: 'Closed spaces', titleRu: 'Закрытые пространства', textEn: 'Stories where a room, hotel, house or institution becomes the main engine of pressure.', textRu: 'Истории, в которых комната, отель, дом или учреждение становятся главным источником давления.', items: [2, 5, 8, 10, 11] },
  { id: 'c3', titleEn: 'Cases that drift into fear', titleRu: 'Дела, которые уходят в страх', textEn: 'Investigations and encounters that begin with reason and end somewhere darker.', textRu: 'Расследования и столкновения, которые начинаются рационально, а заканчиваются во тьме.', items: [4, 9, 10, 11] }
];

window.NEW_TABLE = [7, 4, 9, 10, 3, 8];
window.TOP_TABLE = [2, 11, 1, 5, 6, 9, 7, 4, 10, 8];

window.REVIEW_TABLE = [
  { id: 'r1', movieId: 2, author: 'Anya Morozova', roleEn: 'editor', roleRu: 'редактор', score: '9/10', textEn: 'The hotel works like a living machine here. The tension grows from corridors, silence and repetition as much as from the plot itself.', textRu: 'Здесь отель работает как живая машина. Напряжение рождается из коридоров, тишины и повторения не меньше, чем из сюжета.' },
  { id: 'r2', movieId: 4, author: 'Roman Petrov', roleEn: 'viewer note', roleRu: 'заметка зрителя', score: '8/10', textEn: 'What hits hardest is how ordinary family discomfort becomes unbearable before the openly supernatural layer takes over.', textRu: 'Сильнее всего работает то, как обычный семейный дискомфорт становится невыносимым ещё до того, как история уходит в открытую мистику.' },
  { id: 'r3', movieId: 11, author: 'Mila Orlova', roleEn: 'editor', roleRu: 'редактор', score: '9/10', textEn: 'The island eventually feels less like a place and more like a mental condition.', textRu: 'В какой-то момент остров воспринимается уже не как место, а как состояние сознания.' },
  { id: 'r4', movieId: 7, author: 'Kirill S.', roleEn: 'viewer note', roleRu: 'заметка зрителя', score: '8/10', textEn: 'Daylight horror changes the rhythm completely. Everything is visible, which makes the ritual even stranger.', textRu: 'Дневной хоррор полностью меняет ритм. Всё видно, и именно поэтому ритуал кажется ещё более чужим.' },
  { id: 'r5', movieId: 10, author: 'Daria Kuznetsova', roleEn: 'staff pick', roleRu: 'выбор редакции', score: '7/10', textEn: 'A simple premise that keeps finding new ways to fold fear and memory back into one room.', textRu: 'Очень простая идея, которая постоянно находит новые способы замкнуть страх и память в одном номере.' },
  { id: 'r6', movieId: 1, author: 'Pavel Antonov', roleEn: 'editor', roleRu: 'редактор', score: '9/10', textEn: 'The film still works because it stays controlled for a long time and lets the ritual side carry the last act.', textRu: 'Фильм до сих пор работает благодаря тому, что долго держит строгий контроль и отдаёт финал ритуальной стороне истории.' }
];
